name: Release & Publish

on:
  push:
    branches:
      - actions-cache

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        uses: ./.github/actions/yarn-install
      - name: Build
        run: npm run build
